"use client";
import { Search } from 'lucide-react';

export default function Home() {
  return (
    <main>
      <div className="w-full h-[7vh] bg-black flex items-center fixed top-0 right-0 left-0">
        <h1 className="text-white text-3xl font-bold ml-4">FirstFm</h1>
        
        <div className="absolute left-1/2 transform -translate-x-1/2">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-4 h-4" />
            <input 
              type="text" 
              placeholder="Search friends"
              className="pl-10 pr-4 py-2 bg-gray-800 text-white rounded-full border border-gray-700 focus:outline-none focus:border-blue-500 w-96"
            />
        </div>
      </div>
      
      {/* Texto gigante aqui */}
      <div className="text-black">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum facilisis pharetra purus nec lobortis. Morbi ut lectus libero. Aenean sed fringilla urna. Vivamus et sodales augue. Vivamus id libero mauris. Integer semper faucibus tellus. Sed vestibulum nisi sed volutpat vulputate. Vestibulum sit amet pharetra nisi. Cras nunc lorem, sagittis et auctor at, posuere a odio. Nam tincidunt lectus ac velit malesuada imperdiet. Duis ornare vulputate scelerisque. Quisque non risus eu odio euismod iaculis. Sed interdum risus est, pellentesque suscipit dolor dignissim ut. Vestibulum commodo nisl sit amet varius interdum. Nulla laoreet tellus ante, lacinia vestibulum odio maximus id.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque pulvinar risus ut enim dictum vestibulum. Nulla velit dolor, consectetur quis libero ac, tristique scelerisque risus. Sed ac orci nec ex imperdiet placerat a condimentum est. Vivamus viverra non sapien quis facilisis. In placerat eu sapien eget porta. Donec ac orci facilisis, maximus est ac, fringilla leo. Praesent in tellus non diam sodales dignissim. Nullam imperdiet, leo fermentum bibendum placerat, leo nunc luctus leo, a dictum urna urna eu erat. Mauris pharetra mauris sit amet lorem ullamcorper consequat. In ornare nulla nec justo mollis, a aliquet urna pulvinar.

Quisque et metus dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris id dictum neque, id sodales nisi. Nunc finibus diam at tortor blandit ultrices. Nullam quis scelerisque justo. Integer mollis, nulla sed sagittis sodales, ante est mollis felis, quis vehicula arcu nisl ut nunc. Mauris sagittis ante nec augue pulvinar, eget ornare turpis dignissim. Ut luctus dolor vitae sem molestie semper.

Praesent cursus pellentesque rhoncus. Ut non velit velit. Integer id vestibulum elit. Proin semper neque rhoncus elit finibus, nec faucibus nibh malesuada. Nam dignissim est ac est tincidunt posuere. Curabitur pretium libero eu feugiat suscipit. Quisque scelerisque libero arcu, sit amet aliquet enim tincidunt eget. Cras mollis elit justo, eu vestibulum quam accumsan eu. Sed scelerisque nisi erat, sit amet interdum sem gravida sed. Suspendisse iaculis sed nisl sed porta. Proin placerat odio nec est mattis, eu suscipit velit hendrerit. Donec pretium purus eu tellus euismod, eu tincidunt ipsum fermentum. Donec iaculis iaculis est, eget scelerisque metus. Nam vestibulum purus sed enim tincidunt, elementum dictum massa suscipit. Morbi rhoncus sodales purus, ut scelerisque est ultricies nec. Donec vestibulum, nisl at suscipit pharetra, lectus mi efficitur turpis, interdum tempor turpis mauris eget mi.

Maecenas elementum lacinia feugiat. Aliquam congue non felis nec porttitor. Nam scelerisque fermentum sapien, sed egestas ex pulvinar vitae. Pellentesque justo orci, cursus vel posuere iaculis, ullamcorper in nulla. Vestibulum ac convallis mi. Aenean ut lectus maximus, vestibulum neque non, tincidunt arcu. Pellentesque at risus sit amet nulla laoreet vehicula. Curabitur ac tempus mauris.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum facilisis pharetra purus nec lobortis. Morbi ut lectus libero. Aenean sed fringilla urna. Vivamus et sodales augue. Vivamus id libero mauris. Integer semper faucibus tellus. Sed vestibulum nisi sed volutpat vulputate. Vestibulum sit amet pharetra nisi. Cras nunc lorem, sagittis et auctor at, posuere a odio. Nam tincidunt lectus ac velit malesuada imperdiet. Duis ornare vulputate scelerisque. Quisque non risus eu odio euismod iaculis. Sed interdum risus est, pellentesque suscipit dolor dignissim ut. Vestibulum commodo nisl sit amet varius interdum. Nulla laoreet tellus ante, lacinia vestibulum odio maximus id.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque pulvinar risus ut enim dictum vestibulum. Nulla velit dolor, consectetur quis libero ac, tristique scelerisque risus. Sed ac orci nec ex imperdiet placerat a condimentum est. Vivamus viverra non sapien quis facilisis. In placerat eu sapien eget porta. Donec ac orci facilisis, maximus est ac, fringilla leo. Praesent in tellus non diam sodales dignissim. Nullam imperdiet, leo fermentum bibendum placerat, leo nunc luctus leo, a dictum urna urna eu erat. Mauris pharetra mauris sit amet lorem ullamcorper consequat. In ornare nulla nec justo mollis, a aliquet urna pulvinar.

Quisque et metus dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris id dictum neque, id sodales nisi. Nunc finibus diam at tortor blandit ultrices. Nullam quis scelerisque justo. Integer mollis, nulla sed sagittis sodales, ante est mollis felis, quis vehicula arcu nisl ut nunc. Mauris sagittis ante nec augue pulvinar, eget ornare turpis dignissim. Ut luctus dolor vitae sem molestie semper.

Praesent cursus pellentesque rhoncus. Ut non velit velit. Integer id vestibulum elit. Proin semper neque rhoncus elit finibus, nec faucibus nibh malesuada. Nam dignissim est ac est tincidunt posuere. Curabitur pretium libero eu feugiat suscipit. Quisque scelerisque libero arcu, sit amet aliquet enim tincidunt eget. Cras mollis elit justo, eu vestibulum quam accumsan eu. Sed scelerisque nisi erat, sit amet interdum sem gravida sed. Suspendisse iaculis sed nisl sed porta. Proin placerat odio nec est mattis, eu suscipit velit hendrerit. Donec pretium purus eu tellus euismod, eu tincidunt ipsum fermentum. Donec iaculis iaculis est, eget scelerisque metus. Nam vestibulum purus sed enim tincidunt, elementum dictum massa suscipit. Morbi rhoncus sodales purus, ut scelerisque est ultricies nec. Donec vestibulum, nisl at suscipit pharetra, lectus mi efficitur turpis, interdum tempor turpis mauris eget mi.

Maecenas elementum lacinia feugiat. Aliquam congue non felis nec porttitor. Nam scelerisque fermentum sapien, sed egestas ex pulvinar vitae. Pellentesque justo orci, cursus vel posuere iaculis, ullamcorper in nulla. Vestibulum ac convallis mi. Aenean ut lectus maximus, vestibulum neque non, tincidunt arcu. Pellentesque at risus sit amet nulla laoreet vehicula. Curabitur ac tempus mauris.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum facilisis pharetra purus nec lobortis. Morbi ut lectus libero. Aenean sed fringilla urna. Vivamus et sodales augue. Vivamus id libero mauris. Integer semper faucibus tellus. Sed vestibulum nisi sed volutpat vulputate. Vestibulum sit amet pharetra nisi. Cras nunc lorem, sagittis et auctor at, posuere a odio. Nam tincidunt lectus ac velit malesuada imperdiet. Duis ornare vulputate scelerisque. Quisque non risus eu odio euismod iaculis. Sed interdum risus est, pellentesque suscipit dolor dignissim ut. Vestibulum commodo nisl sit amet varius interdum. Nulla laoreet tellus ante, lacinia vestibulum odio maximus id.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque pulvinar risus ut enim dictum vestibulum. Nulla velit dolor, consectetur quis libero ac, tristique scelerisque risus. Sed ac orci nec ex imperdiet placerat a condimentum est. Vivamus viverra non sapien quis facilisis. In placerat eu sapien eget porta. Donec ac orci facilisis, maximus est ac, fringilla leo. Praesent in tellus non diam sodales dignissim. Nullam imperdiet, leo fermentum bibendum placerat, leo nunc luctus leo, a dictum urna urna eu erat. Mauris pharetra mauris sit amet lorem ullamcorper consequat. In ornare nulla nec justo mollis, a aliquet urna pulvinar.

Quisque et metus dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris id dictum neque, id sodales nisi. Nunc finibus diam at tortor blandit ultrices. Nullam quis scelerisque justo. Integer mollis, nulla sed sagittis sodales, ante est mollis felis, quis vehicula arcu nisl ut nunc. Mauris sagittis ante nec augue pulvinar, eget ornare turpis dignissim. Ut luctus dolor vitae sem molestie semper.

Praesent cursus pellentesque rhoncus. Ut non velit velit. Integer id vestibulum elit. Proin semper neque rhoncus elit finibus, nec faucibus nibh malesuada. Nam dignissim est ac est tincidunt posuere. Curabitur pretium libero eu feugiat suscipit. Quisque scelerisque libero arcu, sit amet aliquet enim tincidunt eget. Cras mollis elit justo, eu vestibulum quam accumsan eu. Sed scelerisque nisi erat, sit amet interdum sem gravida sed. Suspendisse iaculis sed nisl sed porta. Proin placerat odio nec est mattis, eu suscipit velit hendrerit. Donec pretium purus eu tellus euismod, eu tincidunt ipsum fermentum. Donec iaculis iaculis est, eget scelerisque metus. Nam vestibulum purus sed enim tincidunt, elementum dictum massa suscipit. Morbi rhoncus sodales purus, ut scelerisque est ultricies nec. Donec vestibulum, nisl at suscipit pharetra, lectus mi efficitur turpis, interdum tempor turpis mauris eget mi.

Maecenas elementum lacinia feugiat. Aliquam congue non felis nec porttitor. Nam scelerisque fermentum sapien, sed egestas ex pulvinar vitae. Pellentesque justo orci, cursus vel posuere iaculis, ullamcorper in nulla. Vestibulum ac convallis mi. Aenean ut lectus maximus, vestibulum neque non, tincidunt arcu. Pellentesque at risus sit amet nulla laoreet vehicula. Curabitur ac tempus mauris.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum facilisis pharetra purus nec lobortis. Morbi ut lectus libero. Aenean sed fringilla urna. Vivamus et sodales augue. Vivamus id libero mauris. Integer semper faucibus tellus. Sed vestibulum nisi sed volutpat vulputate. Vestibulum sit amet pharetra nisi. Cras nunc lorem, sagittis et auctor at, posuere a odio. Nam tincidunt lectus ac velit malesuada imperdiet. Duis ornare vulputate scelerisque. Quisque non risus eu odio euismod iaculis. Sed interdum risus est, pellentesque suscipit dolor dignissim ut. Vestibulum commodo nisl sit amet varius interdum. Nulla laoreet tellus ante, lacinia vestibulum odio maximus id.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque pulvinar risus ut enim dictum vestibulum. Nulla velit dolor, consectetur quis libero ac, tristique scelerisque risus. Sed ac orci nec ex imperdiet placerat a condimentum est. Vivamus viverra non sapien quis facilisis. In placerat eu sapien eget porta. Donec ac orci facilisis, maximus est ac, fringilla leo. Praesent in tellus non diam sodales dignissim. Nullam imperdiet, leo fermentum bibendum placerat, leo nunc luctus leo, a dictum urna urna eu erat. Mauris pharetra mauris sit amet lorem ullamcorper consequat. In ornare nulla nec justo mollis, a aliquet urna pulvinar.

Quisque et metus dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris id dictum neque, id sodales nisi. Nunc finibus diam at tortor blandit ultrices. Nullam quis scelerisque justo. Integer mollis, nulla sed sagittis sodales, ante est mollis felis, quis vehicula arcu nisl ut nunc. Mauris sagittis ante nec augue pulvinar, eget ornare turpis dignissim. Ut luctus dolor vitae sem molestie semper.

Praesent cursus pellentesque rhoncus. Ut non velit velit. Integer id vestibulum elit. Proin semper neque rhoncus elit finibus, nec faucibus nibh malesuada. Nam dignissim est ac est tincidunt posuere. Curabitur pretium libero eu feugiat suscipit. Quisque scelerisque libero arcu, sit amet aliquet enim tincidunt eget. Cras mollis elit justo, eu vestibulum quam accumsan eu. Sed scelerisque nisi erat, sit amet interdum sem gravida sed. Suspendisse iaculis sed nisl sed porta. Proin placerat odio nec est mattis, eu suscipit velit hendrerit. Donec pretium purus eu tellus euismod, eu tincidunt ipsum fermentum. Donec iaculis iaculis est, eget scelerisque metus. Nam vestibulum purus sed enim tincidunt, elementum dictum massa suscipit. Morbi rhoncus sodales purus, ut scelerisque est ultricies nec. Donec vestibulum, nisl at suscipit pharetra, lectus mi efficitur turpis, interdum tempor turpis mauris eget mi.

Maecenas elementum lacinia feugiat. Aliquam congue non felis nec porttitor. Nam scelerisque fermentum sapien, sed egestas ex pulvinar vitae. Pellentesque justo orci, cursus vel posuere iaculis, ullamcorper in nulla. Vestibulum ac convallis mi. Aenean ut lectus maximus, vestibulum neque non, tincidunt arcu. Pellentesque at risus sit amet nulla laoreet vehicula. Curabitur ac tempus mauris.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum facilisis pharetra purus nec lobortis. Morbi ut lectus libero. Aenean sed fringilla urna. Vivamus et sodales augue. Vivamus id libero mauris. Integer semper faucibus tellus. Sed vestibulum nisi sed volutpat vulputate. Vestibulum sit amet pharetra nisi. Cras nunc lorem, sagittis et auctor at, posuere a odio. Nam tincidunt lectus ac velit malesuada imperdiet. Duis ornare vulputate scelerisque. Quisque non risus eu odio euismod iaculis. Sed interdum risus est, pellentesque suscipit dolor dignissim ut. Vestibulum commodo nisl sit amet varius interdum. Nulla laoreet tellus ante, lacinia vestibulum odio maximus id.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque pulvinar risus ut enim dictum vestibulum. Nulla velit dolor, consectetur quis libero ac, tristique scelerisque risus. Sed ac orci nec ex imperdiet placerat a condimentum est. Vivamus viverra non sapien quis facilisis. In placerat eu sapien eget porta. Donec ac orci facilisis, maximus est ac, fringilla leo. Praesent in tellus non diam sodales dignissim. Nullam imperdiet, leo fermentum bibendum placerat, leo nunc luctus leo, a dictum urna urna eu erat. Mauris pharetra mauris sit amet lorem ullamcorper consequat. In ornare nulla nec justo mollis, a aliquet urna pulvinar.

Quisque et metus dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris id dictum neque, id sodales nisi. Nunc finibus diam at tortor blandit ultrices. Nullam quis scelerisque justo. Integer mollis, nulla sed sagittis sodales, ante est mollis felis, quis vehicula arcu nisl ut nunc. Mauris sagittis ante nec augue pulvinar, eget ornare turpis dignissim. Ut luctus dolor vitae sem molestie semper.

Praesent cursus pellentesque rhoncus. Ut non velit velit. Integer id vestibulum elit. Proin semper neque rhoncus elit finibus, nec faucibus nibh malesuada. Nam dignissim est ac est tincidunt posuere. Curabitur pretium libero eu feugiat suscipit. Quisque scelerisque libero arcu, sit amet aliquet enim tincidunt eget. Cras mollis elit justo, eu vestibulum quam accumsan eu. Sed scelerisque nisi erat, sit amet interdum sem gravida sed. Suspendisse iaculis sed nisl sed porta. Proin placerat odio nec est mattis, eu suscipit velit hendrerit. Donec pretium purus eu tellus euismod, eu tincidunt ipsum fermentum. Donec iaculis iaculis est, eget scelerisque metus. Nam vestibulum purus sed enim tincidunt, elementum dictum massa suscipit. Morbi rhoncus sodales purus, ut scelerisque est ultricies nec. Donec vestibulum, nisl at suscipit pharetra, lectus mi efficitur turpis, interdum tempor turpis mauris eget mi.

Maecenas elementum lacinia feugiat. Aliquam congue non felis nec porttitor. Nam scelerisque fermentum sapien, sed egestas ex pulvinar vitae. Pellentesque justo orci, cursus vel posuere iaculis, ullamcorper in nulla. Vestibulum ac convallis mi. Aenean ut lectus maximus, vestibulum neque non, tincidunt arcu. Pellentesque at risus sit amet nulla laoreet vehicula. Curabitur ac tempus mauris.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum facilisis pharetra purus nec lobortis. Morbi ut lectus libero. Aenean sed fringilla urna. Vivamus et sodales augue. Vivamus id libero mauris. Integer semper faucibus tellus. Sed vestibulum nisi sed volutpat vulputate. Vestibulum sit amet pharetra nisi. Cras nunc lorem, sagittis et auctor at, posuere a odio. Nam tincidunt lectus ac velit malesuada imperdiet. Duis ornare vulputate scelerisque. Quisque non risus eu odio euismod iaculis. Sed interdum risus est, pellentesque suscipit dolor dignissim ut. Vestibulum commodo nisl sit amet varius interdum. Nulla laoreet tellus ante, lacinia vestibulum odio maximus id.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque pulvinar risus ut enim dictum vestibulum. Nulla velit dolor, consectetur quis libero ac, tristique scelerisque risus. Sed ac orci nec ex imperdiet placerat a condimentum est. Vivamus viverra non sapien quis facilisis. In placerat eu sapien eget porta. Donec ac orci facilisis, maximus est ac, fringilla leo. Praesent in tellus non diam sodales dignissim. Nullam imperdiet, leo fermentum bibendum placerat, leo nunc luctus leo, a dictum urna urna eu erat. Mauris pharetra mauris sit amet lorem ullamcorper consequat. In ornare nulla nec justo mollis, a aliquet urna pulvinar.

Quisque et metus dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris id dictum neque, id sodales nisi. Nunc finibus diam at tortor blandit ultrices. Nullam quis scelerisque justo. Integer mollis, nulla sed sagittis sodales, ante est mollis felis, quis vehicula arcu nisl ut nunc. Mauris sagittis ante nec augue pulvinar, eget ornare turpis dignissim. Ut luctus dolor vitae sem molestie semper.

Praesent cursus pellentesque rhoncus. Ut non velit velit. Integer id vestibulum elit. Proin semper neque rhoncus elit finibus, nec faucibus nibh malesuada. Nam dignissim est ac est tincidunt posuere. Curabitur pretium libero eu feugiat suscipit. Quisque scelerisque libero arcu, sit amet aliquet enim tincidunt eget. Cras mollis elit justo, eu vestibulum quam accumsan eu. Sed scelerisque nisi erat, sit amet interdum sem gravida sed. Suspendisse iaculis sed nisl sed porta. Proin placerat odio nec est mattis, eu suscipit velit hendrerit. Donec pretium purus eu tellus euismod, eu tincidunt ipsum fermentum. Donec iaculis iaculis est, eget scelerisque metus. Nam vestibulum purus sed enim tincidunt, elementum dictum massa suscipit. Morbi rhoncus sodales purus, ut scelerisque est ultricies nec. Donec vestibulum, nisl at suscipit pharetra, lectus mi efficitur turpis, interdum tempor turpis mauris eget mi.

Maecenas elementum lacinia feugiat. Aliquam congue non felis nec porttitor. Nam scelerisque fermentum sapien, sed egestas ex pulvinar vitae. Pellentesque justo orci, cursus vel posuere iaculis, ullamcorper in nulla. Vestibulum ac convallis mi. Aenean ut lectus maximus, vestibulum neque non, tincidunt arcu. Pellentesque at risus sit amet nulla laoreet vehicula. Curabitur ac tempus mauris.
      </div>
    </main>
  )
}

